### ISSUE TITLE
Error: an error occured when optimizing with remote solver

### ISSUE THREAD

**Issue by zhiqiangliao** [ds2010/pyStoNED#54]
### Describe the error
My code:
```python
from pystoned import CNLS
from pystoned.constant import CET_ADDI, FUN_PROD, RTS_VRS

# define the CNLS model
model = CNLS.CNLS(y_tr, x_tr, z=None, cet = CET_ADDI, fun = FUN_PROD, rts = RTS_VRS)
# solve the model with remote solver
model.optimize('xxx@gmail.com')
```
The result:
```
Estimating the additive model remotely with mosek solver.
ERROR: Error parsing NEOS solution file  NEOS log: Job 13110247 dispatched
password: IcCbDRGl
    ---------- Begin Solver Output -----------
    Condor submit: 'neos.submit' Condor submit: 'watchdog.submit' Job
    submitted to NEOS HTCondor pool.
Traceback (most recent call last):
  File "/home/zhiqiang/.local/lib/python3.10/site-packages/pyomo/opt/plugins/sol.py", line 41, in __call__
    return self._load(f, res, soln, suffixes)
  File "/home/zhiqiang/.local/lib/python3.10/site-packages/pyomo/opt/plugins/sol.py", line 83, in _load
    raise ValueError("no Options line found")
ValueError: no Options line found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhiqiang/.local/lib/python3.10/site-packages/pyomo/neos/plugins/kestrel_plugin.py", line 219, in _perform_wait_any
    solver_results = opt.process_output(rc)
  File "/home/zhiqiang/.local/lib/python3.10/site-packages/pyomo/opt/solver/shellcmd.py", line 396, in process_output
    results = self._results_reader(
  File "/home/zhiqiang/.local/lib/python3.10/site-packages/pyomo/opt/plugins/sol.py", line 45, in __call__
    raise ValueError(
ValueError: Error reading '/tmp/tmphe6jan6i.neos.sol': no Options line found.
SOL File Output:
ERROR: An error occured with your submission.

ERROR: ERROR: An error occured with your submission.
```

**Comment by ds2010** [comment]
@Fangop, Could you please take care of this unexpected issue? Thanks in advance!

Here is a simple replication example:

```python
# import packages
import numpy as np
from pystoned import CNLS
from pystoned.plot import plot2d
from pystoned.constant import CET_ADDI, FUN_PROD, RTS_VRS

# set seed
np.random.seed(0)

# generate DMUs: DGP
x = np.sort(np.random.uniform(low=1, high=10, size=50))
u = np.abs(np.random.normal(loc=0, scale=0.7, size=50))
y_true = 3 + np.log(x)
y = y_true - u

# define the CNLS model
model = CNLS.CNLS(y, x, z=None, cet = CET_ADDI, fun = FUN_PROD, rts = RTS_VRS)
model.optimize('email@address')
model.display_residual()
```

**Comment by Fangop** [comment]
Hi, @zhiqiangliao @ds2010 

It seems like there is some problem with mosek solver or gurobi solver on Remote NEOS server.

The knitro solver works as usual.
I'll check if there are some substitution for this.

**Comment by ds2010** [comment]
Thank you, @Fangop. I think it might be related to the update of `sol.py` in the recent `pyomo` versions.

I have opened an new issue in the `pyomo` repo. So, let's see how they fix this issue.

**Comment by ds2010** [comment]
This issue actually arises from the NEOS side. See this [reply](https://github.com/Pyomo/pyomo/issues/2867).

We will update it accordingly.
